#ifndef APPLING_VERSION_H
#define APPLING_VERSION_H

#define APPLING_VERSION_MAJOR 1
#define APPLING_VERSION_MINOR 0
#define APPLING_VERSION_PATCH 0

#define APPLING_STRING_LITERAL(x) #x
#define APPLING_STRING(x)         APPLING_STRING_LITERAL(x)

#define APPLING_VERSION APPLING_STRING(APPLING_VERSION_MAJOR) "." APPLING_STRING(APPLING_VERSION_MINOR) "." APPLING_STRING(APPLING_VERSION_PATCH)

#endif // APPLING_VERSION_H
