name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: macos-latest
          platform: darwin
          arch: arm64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install -g drives
    - run: drives mirror qogbhqbcxknrpeotyz7hk4x3mxuf6d9mhb1dxm6ms5sdn6hh1uso prebuilds
