name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: macos-latest
          platform: darwin
          arch: arm64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: build/corestore
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: choco upgrade llvm
      if: ${{ matrix.platform == 'win32' }}
    - run: get-netfirewallprofile | set-netfirewallprofile -enabled false
      shell: pwsh
      if: ${{ matrix.platform == 'win32' }}
    - run: npm install -g bare-make
    - run: npm install
    - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --debug
    - run: bare-make build
    - run: bare-make test
